In [9]:
import pickle
import pandas as pd
import numpy as np


In [6]:
ohe_sex=pickle.load(open("models/ohe_sex.pkl","rb"))
ohe_embarked=pickle.load(open("models/ohe_embarked.pkl","rb"))
dtc=pickle.load(open("models/dtc.pkl","rb"))

In [19]:
#Assume user input
test_input=np.array([2,"male",31.0,0,0,10.5,"S"],dtype=object).reshape(1,7)

In [20]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [26]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\maner\OneDrive\Desktop\ML Practice\MLenv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [28]:
test_input_sex

array([[0., 1.]])

In [30]:
test_input_embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [32]:
test_input_embarked

array([[0., 0., 1.]])

In [34]:
test_input_age=test_input[:,2].reshape(1,1)

In [36]:
test_input_age

array([[31.0]], dtype=object)

In [38]:
test_input_transformed=np.concat([test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked],axis=1)

In [41]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [43]:
test_input_transformed.shape

(1, 10)

In [44]:
dtc.predict(test_input_transformed)

c:\Users\maner\OneDrive\Desktop\ML Practice\MLenv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])