In [1]:
import pandas as pd
import numpy as np

In [2]:
titanic=pd.read_csv("titanic.csv")

In [3]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [4]:
titanic.shape

(891, 12)

In [5]:
titanic=titanic[["Survived","Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]]

In [6]:
titanic.head(2)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,22.0,1,0,7.2500,S
1,1,1,female,38.0,1,0,71.2833,C


In [7]:
titanic.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [8]:
titanic["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [9]:
titanic["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [10]:
titanic.head(2)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,22.0,1,0,7.2500,S
1,1,1,female,38.0,1,0,71.2833,C


train_test_split

In [11]:
from sklearn.model_selection import train_test_split

x=titanic.drop(columns=["Survived"])
y=titanic["Survived"]

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
x_train.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5000,S
733,2,male,23.0,0,0,13.0000,S
382,3,male,32.0,0,0,7.9250,S
704,3,male,26.0,1,0,7.8542,S
813,3,female,6.0,4,2,31.2750,S


In [14]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [15]:
from sklearn.impute import SimpleImputer #age&embarked

si_age=SimpleImputer()
si_embarked=SimpleImputer(strategy="most_frequent")

x_train_age=si_age.fit_transform(x_train[["Age"]])
x_train_embarked=si_embarked.fit_transform(x_train[["Embarked"]])

x_test_age=si_age.transform(x_test[["Age"]])
x_test_embarked=si_embarked.transform(x_test[["Embarked"]])



In [16]:
x_train_age

array([[45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [29.49884615],
       [29.        ],
       [36.        ],
       [29.49884615],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [29.49884615],
       [29.49884615],
       [24.        ],
       [18.        ],
       [29.49884615],
       [25

In [17]:
x_train_embarked

array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['Q'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

one hot encoding on --->sex,embarked

In [18]:
from sklearn.preprocessing import OneHotEncoder

ohe_sex=OneHotEncoder(sparse_output=False,handle_unknown="ignore")
ohe_embarked=OneHotEncoder(sparse_output=False,handle_unknown="ignore")

x_train_sex=ohe_sex.fit_transform(x_train[["Sex"]])
x_train_embarked=ohe_embarked.fit_transform(x_train_embarked)

x_test_sex=ohe_sex.transform(x_test[["Sex"]])
x_test_embarked=ohe_embarked.transform(x_test_embarked)

In [19]:
x_train_sex

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]], shape=(712, 2))

In [20]:
x_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(712, 3))

In [21]:
x_train.head(2)

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5,S
733,2,male,23.0,0,0,13.0,S


In [22]:
x_train_rem=x_train[["Pclass","SibSp","Parch","Fare"]]
x_test_rem=x_test[["Pclass","SibSp","Parch","Fare"]]

In [23]:
x_train_rem.head(1)

,Pclass,SibSp,Parch,Fare
331,1,0,0,28.5


In [70]:
#concatenate

In [24]:
x_train_transformed=np.concatenate((x_train_rem,x_train_age,x_train_sex,x_train_embarked),axis=1)

In [25]:
x_train_transformed

array([[1., 0., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       ...,
       [3., 2., 0., ..., 0., 0., 1.],
       [1., 1., 2., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.]], shape=(712, 10))

In [26]:
x_test_transformed=np.concatenate((x_test_rem,x_test_age,x_test_sex,x_test_embarked),axis=1)

In [27]:
x_test_transformed

array([[3., 1., 1., ..., 1., 0., 0.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       ...,
       [3., 1., 5., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 1., 1., ..., 0., 0., 1.]], shape=(179, 10))

In [28]:
x_train_age

array([[45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [29.49884615],
       [29.49884615],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [29.49884615],
       [29.        ],
       [36.        ],
       [29.49884615],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [29.49884615],
       [29.49884615],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [29.49884615],
       [29.49884615],
       [24.        ],
       [18.        ],
       [29.49884615],
       [25

In [29]:
pd.DataFrame(x_train_age,columns=["Age"])

,Age
0,45.500000
1,23.000000
2,32.000000
3,26.000000
4,6.000000
...,...
707,21.000000
708,29.498846
709,41.000000
710,14.000000


In [30]:
x_train_age_df=pd.DataFrame(x_train_age,columns=["Age"],index=x_train.index)

In [31]:
x_train_age_df

,Age
331,45.500000
733,23.000000
382,32.000000
704,26.000000
813,6.000000
...,...
106,21.000000
270,29.498846
860,41.000000
435,14.000000


In [33]:
pd.DataFrame(x_train_sex,columns=ohe_sex.get_feature_names_out())

,Sex_female,Sex_male
0,0.0,1.0
1,0.0,1.0
2,0.0,1.0
3,0.0,1.0
4,1.0,0.0
...,...,...
707,1.0,0.0
708,0.0,1.0
709,0.0,1.0
710,1.0,0.0


In [34]:
x_train_sex_df=pd.DataFrame(x_train_sex,columns=ohe_sex.get_feature_names_out(["Sex"]),index=x_train.index)

In [35]:
x_train_sex_df

,Sex_female,Sex_male
331,0.0,1.0
733,0.0,1.0
382,0.0,1.0
704,0.0,1.0
813,1.0,0.0
...,...,...
106,1.0,0.0
270,0.0,1.0
860,0.0,1.0
435,1.0,0.0


In [36]:
pd.DataFrame(x_train_embarked,columns=ohe_embarked.get_feature_names_out())

,x0_C,x0_Q,x0_S
0,0.0,0.0,1.0
1,0.0,0.0,1.0
2,0.0,0.0,1.0
3,0.0,0.0,1.0
4,0.0,0.0,1.0
...,...,...,...
707,0.0,0.0,1.0
708,0.0,0.0,1.0
709,0.0,0.0,1.0
710,0.0,0.0,1.0


In [37]:
pd.DataFrame(x_train_embarked,columns=ohe_embarked.get_feature_names_out(["Embarked"]))

,Embarked_C,Embarked_Q,Embarked_S
0,0.0,0.0,1.0
1,0.0,0.0,1.0
2,0.0,0.0,1.0
3,0.0,0.0,1.0
4,0.0,0.0,1.0
...,...,...,...
707,0.0,0.0,1.0
708,0.0,0.0,1.0
709,0.0,0.0,1.0
710,0.0,0.0,1.0


In [38]:
x_train_embarked_df=pd.DataFrame(x_train_embarked,columns=ohe_embarked.get_feature_names_out(["Embarked"]),index=x_train.index)

#Sex kept names because encoder got a DataFrame, 
# but Embarked lost names because SimpleImputer converted it into NumPy array first.that why we write Embarked inside it.

In [39]:
x_train_embarked_df

,Embarked_C,Embarked_Q,Embarked_S
331,0.0,0.0,1.0
733,0.0,0.0,1.0
382,0.0,0.0,1.0
704,0.0,0.0,1.0
813,0.0,0.0,1.0
...,...,...,...
106,0.0,0.0,1.0
270,0.0,0.0,1.0
860,0.0,0.0,1.0
435,0.0,0.0,1.0


In [40]:
x_train_rem

,Pclass,SibSp,Parch,Fare
331,1,0,0,28.5000
733,2,0,0,13.0000
382,3,0,0,7.9250
704,3,1,0,7.8542
813,3,4,2,31.2750
...,...,...,...,...
106,3,0,0,7.6500
270,1,0,0,31.0000
860,3,2,0,14.1083
435,1,1,2,120.0000


In [41]:
x_train_transformed_df=pd.concat([x_train_rem,x_train_age_df,x_train_sex_df,x_train_embarked_df],axis=1)

In [43]:
x_train_transformed_df

,Pclass,SibSp,Parch,Fare,Age,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
331,1,0,0,28.5000,45.500000,0.0,1.0,0.0,0.0,1.0
733,2,0,0,13.0000,23.000000,0.0,1.0,0.0,0.0,1.0
382,3,0,0,7.9250,32.000000,0.0,1.0,0.0,0.0,1.0
704,3,1,0,7.8542,26.000000,0.0,1.0,0.0,0.0,1.0
813,3,4,2,31.2750,6.000000,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
106,3,0,0,7.6500,21.000000,1.0,0.0,0.0,0.0,1.0
270,1,0,0,31.0000,29.498846,0.0,1.0,0.0,0.0,1.0
860,3,2,0,14.1083,41.000000,0.0,1.0,0.0,0.0,1.0
435,1,1,2,120.0000,14.000000,1.0,0.0,0.0,0.0,1.0


In [45]:
x_test

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
709,3,male,NaN,1,1,15.2458,C
439,2,male,31.0,0,0,10.5000,S
840,3,male,20.0,0,0,7.9250,S
720,2,female,6.0,0,1,33.0000,S
39,3,female,14.0,1,0,11.2417,C
...,...,...,...,...,...,...,...
433,3,male,17.0,0,0,7.1250,S
773,3,male,NaN,0,0,7.2250,C
25,3,female,38.0,1,5,31.3875,S
84,2,female,17.0,0,0,10.5000,S


In [48]:
pd.DataFrame(x_test_age,columns=["Age"])

,Age
0,29.498846
1,31.000000
2,20.000000
3,6.000000
4,14.000000
...,...
174,17.000000
175,29.498846
176,38.000000
177,17.000000


In [51]:
x_test_age_df=pd.DataFrame(x_test_age,columns=["Age"],index=x_test.index)

In [53]:
x_test_age_df

,Age
709,29.498846
439,31.000000
840,20.000000
720,6.000000
39,14.000000
...,...
433,17.000000
773,29.498846
25,38.000000
84,17.000000


In [56]:
pd.DataFrame(x_test_sex,columns=ohe_sex.get_feature_names_out())

,Sex_female,Sex_male
0,0.0,1.0
1,0.0,1.0
2,0.0,1.0
3,1.0,0.0
4,1.0,0.0
...,...,...
174,0.0,1.0
175,0.0,1.0
176,1.0,0.0
177,1.0,0.0


In [59]:
x_test_sex_df=pd.DataFrame(x_test_sex,columns=ohe_sex.get_feature_names_out(),index=x_test.index)

In [61]:
x_test_sex_df

,Sex_female,Sex_male
709,0.0,1.0
439,0.0,1.0
840,0.0,1.0
720,1.0,0.0
39,1.0,0.0
...,...,...
433,0.0,1.0
773,0.0,1.0
25,1.0,0.0
84,1.0,0.0


In [67]:
x_test_embarked_df=pd.DataFrame(x_test_embarked,columns=ohe_embarked.get_feature_names_out(["Embarked"]),index=x_test.index)

In [69]:
x_test_embarked_df

,Embarked_C,Embarked_Q,Embarked_S
709,1.0,0.0,0.0
439,0.0,0.0,1.0
840,0.0,0.0,1.0
720,0.0,0.0,1.0
39,1.0,0.0,0.0
...,...,...,...
433,0.0,0.0,1.0
773,1.0,0.0,0.0
25,0.0,0.0,1.0
84,0.0,0.0,1.0


In [71]:
x_test_rem

,Pclass,SibSp,Parch,Fare
709,3,1,1,15.2458
439,2,0,0,10.5000
840,3,0,0,7.9250
720,2,0,1,33.0000
39,3,1,0,11.2417
...,...,...,...,...
433,3,0,0,7.1250
773,3,0,0,7.2250
25,3,1,5,31.3875
84,2,0,0,10.5000


In [75]:
x_test_transformed_df=pd.concat([x_test_rem,x_test_age_df,x_test_sex_df,x_test_embarked_df],axis=1)

In [78]:
x_test_transformed_df

,Pclass,SibSp,Parch,Fare,Age,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
709,3,1,1,15.2458,29.498846,0.0,1.0,1.0,0.0,0.0
439,2,0,0,10.5000,31.000000,0.0,1.0,0.0,0.0,1.0
840,3,0,0,7.9250,20.000000,0.0,1.0,0.0,0.0,1.0
720,2,0,1,33.0000,6.000000,1.0,0.0,0.0,0.0,1.0
39,3,1,0,11.2417,14.000000,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
433,3,0,0,7.1250,17.000000,0.0,1.0,0.0,0.0,1.0
773,3,0,0,7.2250,29.498846,0.0,1.0,1.0,0.0,0.0
25,3,1,5,31.3875,38.000000,1.0,0.0,0.0,0.0,1.0
84,2,0,0,10.5000,17.000000,1.0,0.0,0.0,0.0,1.0


In [80]:
x_train_transformed_df.head(2)

,Pclass,SibSp,Parch,Fare,Age,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
331,1,0,0,28.5,45.5,0.0,1.0,0.0,0.0,1.0
733,2,0,0,13.0,23.0,0.0,1.0,0.0,0.0,1.0


In [82]:
x_train_transformed_df.shape

(712, 10)

In [83]:
x_test_transformed_df.head(2)

,Pclass,SibSp,Parch,Fare,Age,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
709,3,1,1,15.2458,29.498846,0.0,1.0,1.0,0.0,0.0
439,2,0,0,10.5000,31.000000,0.0,1.0,0.0,0.0,1.0


In [85]:
x_test_transformed_df.shape

(179, 10)

ALGORITHM-->Decisiontreeclassifier

In [88]:
from sklearn.tree import DecisionTreeClassifier

In [102]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train_transformed_df,y_train)

y_pred=dtc.predict(x_test_transformed_df)

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.7932960893854749

In [104]:
import pickle

In [109]:
pickle.dump(ohe_sex,open("models/ohe_sex.pkl","wb"))
pickle.dump(ohe_embarked,open("models/ohe_embarked.pkl","wb"))
pickle.dump(dtc,open("models/dtc.pkl","wb"))

In [110]:
x_train.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5000,S
733,2,male,23.0,0,0,13.0000,S
382,3,male,32.0,0,0,7.9250,S
704,3,male,26.0,1,0,7.8542,S
813,3,female,6.0,4,2,31.2750,S
