In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer    

In [4]:
# define:apply different different transformation technique on different columns.

In [6]:
df=pd.read_csv("covid_toy.csv")

In [8]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [10]:
df.shape

(100, 6)

In [ ]:
#gender,city-->nominal categorical data -->ohe
#cough-->ordinal categorical data  -->oe
#age-->numerical-->scaler,but in this we not gonna apply
#fever-->num,but having missing value-->simpleImputer
#has_covid--> do label encoding


In [15]:
df["cough"].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [17]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [19]:
df["gender"].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [26]:
df.isnull().sum()  #so fever having 10 missing val.

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    str    
 2   fever      90 non-null     float64
 3   cough      100 non-null    str    
 4   city       100 non-null    str    
 5   has_covid  100 non-null    str    
dtypes: float64(1), int64(1), str(4)
memory usage: 4.8 KB


In [30]:
df.head(3)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No


In [34]:
from sklearn.model_selection import train_test_split
x=df.drop(columns=["has_covid"])
y=df["has_covid"]

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [38]:
x_train

,age,gender,fever,cough,city
43,22,Female,99.0,Mild,Bangalore
62,56,Female,104.0,Strong,Bangalore
3,31,Female,98.0,Mild,Kolkata
71,75,Female,104.0,Strong,Delhi
45,72,Male,99.0,Mild,Bangalore
...,...,...,...,...,...
96,51,Female,101.0,Strong,Kolkata
67,65,Male,99.0,Mild,Bangalore
64,42,Male,104.0,Mild,Mumbai
47,18,Female,104.0,Mild,Bangalore


In [40]:
y_train

43    Yes
62    Yes
3      No
71     No
45     No
     ... 
96    Yes
67     No
64     No
47     No
44     No
Name: has_covid, Length: 80, dtype: str

WITHOUT COLUMNS_TRANFORMATION

In [ ]:
#simpleImputer--->fever column

from sklearn.impute import SimpleImputer
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[["fever"]])
x_test_fever=si.transform(x_test[["fever"]])

In [45]:
x_train_fever

array([[ 99.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.91549296],
       [100.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [100.91549296],
       [100.91549296],
       [104.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [103.        ],
       [104.        ],
       [ 99

In [47]:
x_train_fever.shape

(80, 1)

In [48]:
df["cough"].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [50]:
#ordinalEncoding--->cough column

oe=OrdinalEncoder(categories=[["Mild","Strong"]])
x_train_cough=oe.fit_transform(x_train[["cough"]])
x_test_cough=oe.transform(x_test[["cough"]])

In [52]:
x_train_cough

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],

In [88]:
x_train_cough.shape

(80, 1)

In [58]:
x_train.head(2)

,age,gender,fever,cough,city
43,22,Female,99.0,Mild,Bangalore
62,56,Female,104.0,Strong,Bangalore


In [61]:
#onehotencoding--->gender,city

ohe=OneHotEncoder(sparse_output=False,drop="first")

x_train_gender_city=ohe.fit_transform(x_train[["gender","city"]])
x_test_gender_city=ohe.transform(x_test[["gender","city"]])


In [66]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [ ]:
x_train_gender_city  #gender--->male,female &city-->kolkata,banglore,delhi,mumbai
                      # drop="first" from 2 categories 1,1,dummy_var remove,use this to avoid multicollinearity problem

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],


In [67]:
x_train_gender_city.shape

(80, 4)

In [68]:
#fetching age from x_train

In [89]:
x_train_age=x_train[["age"]].values
x_test_age=x_test[["age"]].values

In [90]:
x_train_age

array([[22],
       [56],
       [31],
       [75],
       [72],
       [66],
       [14],
       [10],
       [24],
       [80],
       [24],
       [14],
       [59],
       [54],
       [11],
       [33],
       [64],
       [71],
       [10],
       [34],
       [27],
       [81],
       [27],
       [82],
       [65],
       [70],
       [40],
       [49],
       [49],
       [84],
       [38],
       [ 6],
       [60],
       [74],
       [16],
       [19],
       [65],
       [82],
       [80],
       [47],
       [75],
       [83],
       [51],
       [49],
       [48],
       [16],
       [34],
       [69],
       [51],
       [46],
       [42],
       [34],
       [44],
       [20],
       [ 5],
       [73],
       [12],
       [79],
       [83],
       [ 8],
       [23],
       [55],
       [65],
       [19],
       [50],
       [69],
       [23],
       [25],
       [ 5],
       [68],
       [47],
       [38],
       [73],
       [17],
       [64],
       [51],
       [65],

In [91]:
x_train_age.shape

(80, 1)

In [92]:
x_train.head(1)

,age,gender,fever,cough,city
43,22,Female,99.0,Mild,Bangalore


now concat them 

In [94]:
x_train_transformed=np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)

In [97]:
x_train_transformed

array([[ 22.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 56.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 75.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 72.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 66.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 14.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 10.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 24.        ,  98.        ,   1.        ,   0.        ,
          1.    

In [99]:
x_train_transformed.shape

(80, 7)

In [101]:
x_test_transformed=np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

In [103]:
x_test_transformed

array([[ 19.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 25.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 42.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 81.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [  5.        , 102.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 69.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 60.        ,  99.        ,   0.        ,   0.        ,
          0.    

In [105]:
x_test_transformed.shape

(20, 7)

In [106]:
#without column transform technique ,take too much time 
#now with column transform,it will take less time ,solved in single of code

WITH COLUMN TRANFORMATION   

In [124]:
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer([
    ("trf1",SimpleImputer(),["fever"]),
    ("trf2",OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),
    ("trf3",OneHotEncoder(sparse_output=False,drop="first"),["gender","city"]),
    ],remainder="passthrough")

In [132]:
ct_train_transformed=ct.fit_transform(x_train)


In [133]:
ct_train_transformed

array([[ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  66.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  14.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  10.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          1.    

In [136]:
ct_train_transformed.shape

(80, 7)

In [134]:
ct_test_transformed=ct.transform(x_test)

In [135]:
ct_test_transformed

array([[100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  25.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  27.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  69.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [137]:
ct_test_transformed.shape

(20, 7)

In [119]:
#but its look hard to see,no column name,so convert it into dataframe

In [139]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [141]:
ct_train_transformed_df=pd.DataFrame(ct_train_transformed,columns=ct.get_feature_names_out())

In [142]:
ct_train_transformed_df

,trf1__fever,trf2__cough,trf3__gender_Male,trf3__city_Delhi,trf3__city_Kolkata,trf3__city_Mumbai,remainder__age
0,99.0,0.0,0.0,0.0,0.0,0.0,22.0
1,104.0,1.0,0.0,0.0,0.0,0.0,56.0
2,98.0,0.0,0.0,0.0,1.0,0.0,31.0
3,104.0,1.0,0.0,1.0,0.0,0.0,75.0
4,99.0,0.0,1.0,0.0,0.0,0.0,72.0
...,...,...,...,...,...,...,...
75,101.0,1.0,0.0,0.0,1.0,0.0,51.0
76,99.0,0.0,1.0,0.0,0.0,0.0,65.0
77,104.0,0.0,1.0,0.0,0.0,1.0,42.0
78,104.0,0.0,0.0,0.0,0.0,0.0,18.0


In [144]:
ct_train_transformed_df.shape

(80, 7)

In [146]:
ct_test_transformed_df=pd.DataFrame(ct_test_transformed,columns=ct.get_feature_names_out())

In [147]:
ct_test_transformed_df

,trf1__fever,trf2__cough,trf3__gender_Male,trf3__city_Delhi,trf3__city_Kolkata,trf3__city_Mumbai,remainder__age
0,100.000000,0.0,0.0,0.0,1.0,0.0,19.0
1,104.000000,0.0,1.0,0.0,0.0,0.0,25.0
2,101.000000,0.0,1.0,1.0,0.0,0.0,42.0
3,101.000000,0.0,0.0,0.0,0.0,1.0,81.0
4,102.000000,0.0,1.0,0.0,1.0,0.0,5.0
5,100.000000,0.0,1.0,0.0,1.0,0.0,27.0
6,103.000000,0.0,0.0,0.0,1.0,0.0,69.0
7,98.000000,1.0,1.0,0.0,1.0,0.0,34.0
8,99.000000,0.0,0.0,0.0,0.0,1.0,60.0
9,104.000000,0.0,0.0,0.0,0.0,0.0,12.0


In [148]:
ct_test_transformed_df.shape

(20, 7)